export { default as Home } from './Home'
export { default as About } from './About'
export { default as Package } from './Package'
export { default as Materials } from './Materials'
export { default as Labels } from './Labels'
export { default as Equipment } from './Equipment'
export { default as Contacts } from './Contacts'
export { default as PAGES_DATA } from './data'
