import { Grid, GridItem, VStack } from "@chakra-ui/react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { hasLocale, NextIntlClientProvider } from "next-intl"
import { notFound } from "next/navigation"
import { setRequestLocale } from "next-intl/server"

import { routing } from "@/i18n/routing"
import { Navbar } from "@/compounds/NavBar/NavBar"

import Provider from "./provider"

const inter = Inter({
  subsets: ["cyrillic", "latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const generateStaticParams = () => {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  setRequestLocale(locale)

  return (
    <html className={inter.className} suppressHydrationWarning lang={locale}>
      <head />
      <body>
        <NextIntlClientProvider>
          <Provider>
            <Grid
              gridTemplateColumns="100%"
              gridTemplateRows="1fr auto"
              position="absolute"
              left="0"
              right="0"
              top="0"
              bottom="0"
              pb={0}
            >
              <GridItem>
                <Navbar />

                <VStack width="100%" gap={0}>
                  {children}
                </VStack>
              </GridItem>

              <GridItem>Footer</GridItem>
            </Grid>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
