import { Container, Grid, GridItem, VStack } from "@chakra-ui/react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { hasLocale, NextIntlClientProvider } from "next-intl"
import { notFound } from "next/navigation"
import { setRequestLocale } from "next-intl/server"

import { routing } from "@/i18n/routing"
import { Navbar } from "@/compounds/NavBar/NavBar"

import Provider from "./provider"

import "@/styles/global.css"
import "swiper/css"
import "swiper/css/navigation"
import "swiper/css/pagination"
import "swiper/css/autoplay"

const inter = Inter({
  subsets: ["cyrillic", "latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const generateStaticParams = () => {
  return routing.locales.map((locale) => ({ locale }))
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params
  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  setRequestLocale(locale)

  return (
    <html className={inter.className} suppressHydrationWarning lang={locale}>
      <head>
        <link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>

      <body>
        <NextIntlClientProvider>
          <Provider>
            <Container>
              <Grid
                gridTemplateColumns="100%"
                gridTemplateRows="93px 1fr 200px"
                width="full"
                height="full"
              >
                <GridItem position="sticky" top="0" zIndex="sticky">
                  <VStack
                    minW="335px"
                    maxW="1200px"
                    height="100%"
                    margin="auto"
                    gap={0}
                  >
                    <Navbar />
                  </VStack>
                </GridItem>

                <GridItem>
                  <VStack
                    minW="335px"
                    maxW="1200px"
                    // width={{ base: "335px", xl: "1200px" }}
                    margin="auto"
                    gap={0}
                  >
                    {children}
                  </VStack>
                </GridItem>

                <GridItem>
                  <VStack
                    minW="335px"
                    maxW="1200px"
                    margin="auto"
                    gap={0}
                  >
                    Footer
                  </VStack>
                </GridItem>
              </Grid>
            </Container>
          </Provider>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
