import { Grid, GridItem, VStack } from "@chakra-ui/react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

import { Navbar } from "@/components/NavBar/NavBar"

import Provider from "./provider"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={inter.className} suppressHydrationWarning>
      <head />
      <body>
        <Provider>
          <Grid
            gridTemplateColumns="100%"
            gridTemplateRows="1fr auto"
            position="absolute"
            left="0"
            right="0"
            top="0"
            bottom="0"
            pb={0}
          >
            <GridItem>
              <Navbar />

              <VStack width="100%" gap={0}>
                {children}
              </VStack>
            </GridItem>

            <GridItem>Footer</GridItem>
          </Grid>
        </Provider>
      </body>
    </html>
  )
}
